### ISSUE TITLE
No hold click behavior for mines + No shocked smiley graphic :(

### ISSUE THREAD

**Issue by Startacker** [KittyKittyKitKat/FreeForm-Minesweeper#11]
Original minesweeper has a held-down click mechanic for mines where holding down left click depresses a cell, but does not reveal it. This would be nice for redirecting or cancelling reveals in the case of a misclick. Also, this would have the potential of implementing the shocked smiley expression ( :O ) while in a held-down state.

**Comment by KittyKittyKitKat** [comment]
This feature is now slated to release in version 2.1
