### ISSUE TITLE
Saving board layouts on Windows does not auto-fill file extension

### ISSUE THREAD

**Issue by asteriskblue** [KittyKittyKitKat/FreeForm-Minesweeper#3]
Playing this game on Windows 10, very fun by the way.

![image](https://user-images.githubusercontent.com/47119412/120405459-9287c400-c316-11eb-817b-739145d929af.png)
When I save a board layout, it seems like it auto-fills the extension, but it actually doesn't. 

![image](https://user-images.githubusercontent.com/47119412/120405522-ba772780-c316-11eb-8728-0d61df39240d.png)
I have to manually type out the file extension for it to work. Can you fix this? :)

**Comment by KittyKittyKitKat** [comment]
This issue has been solved and merged to main. Closing issue report
